# Generated by Django 4.0.4 on 2022-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_profile_ecology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profile',
            name='ecology',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='med_spravka',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='strakhovka',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='talon',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tax',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tech_osmotr',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tech_passport',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tonirovka',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='udost_von_gas_balon_auto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
