# Generated by Django 4.0.4 on 2022-08-05 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_profile_ecology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profile',
            name='ecology',
            field=models.FileField(blank=True, null=True, upload_to='ecology/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='med_spravka',
            field=models.FileField(blank=True, null=True, upload_to='med_spravka/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='passport',
            field=models.FileField(upload_to='passports/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='strakhovka',
            field=models.FileField(blank=True, null=True, upload_to='strakhovka/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='talon',
            field=models.FileField(blank=True, null=True, upload_to='talon/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tax',
            field=models.FileField(blank=True, null=True, upload_to='taxes/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tech_osmotr',
            field=models.FileField(blank=True, null=True, upload_to='tech_osmotr/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tech_passport',
            field=models.FileField(blank=True, null=True, upload_to='tech_passports/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='tonirovka',
            field=models.FileField(blank=True, null=True, upload_to='tonirovka/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='udost_von_gas_balon_auto',
            field=models.FileField(blank=True, null=True, upload_to='udost_von_gas_balon_auto/<function user_directory_path at 0x0000021A23E25D30>'),
        ),
        migrations.AlterField(
            model_name='users_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
